name: console-img
version: 0.1.0.0
synopsis: View an image in the console
author: doublescale
maintainer: doublescale@tutanota.com

executable:
  main: Main.hs
  source-dirs: src
  ghc-options:
    - -threaded
    - -Wall
    - -Werror
    - -O2
  dependencies:
    - base
    - JuicyPixels
